### ISSUE TITLE
Add support for SPIR-V 1.6

### ISSUE THREAD

**Issue by Calinou** [aras-p/smol-v#13]
I've tried to modify Godot to emit SPIR-V 1.6 from its glslang implementation when Vulkan 1.3 support is detected on the driver (as [Vulkan 1.3 mandates support for SPIR-V 1.6](https://registry.khronos.org/vulkan/specs/1.2/html/chap37.html)).

If you want to test this out on your end, you can modify the constants here and recompile: https://github.com/godotengine/godot/blob/541674d10692cf608f1245d7eede459bdc96b74f/modules/glslang/register_types.cpp#L58-L59

However, this causes SMOL-V to fail as it can only compress SPIR-V up to 1.5, not 1.6.
Are there any plans to support SPIR-V 1.6? I assume this would allow for further optimization. Godot compiles its SPIR-V files at runtime, so it can still support older Vulkan versions while benefiting from Vulkan 1.3 drivers when available.

**Comment by aras-p** [comment]
Should be fixed now, but admittedly I only tested it on like three shaders :)
