### ISSUE TITLE
Shifting signed 32-bit value by 31 bits is undefined behaviour

### ISSUE THREAD

**Issue by sagaceilo** [aras-p/smol-v#7]
As in the title.
- https://github.com/aras-p/smol-v/blob/9a787d1354a9e43c9ea6027cd310ce2a2fd78901/source/smolv.cpp#L1167

**Comment by aras-p** [comment]
Technically yes (though clang's ubsan does not complain about it); in practice this happens to do the exactly needed thing (extend sign into all 32 bits) here, on all compilers/platforms that I ever cared about.

Is there a more portable way of easily achieving "splat sign bit into all 32 bits", that is compiled into efficient code?
